/** `views/ResourceView.vue` 渲染的业务目录页面，一个页面一个文件（文件名 = 资源 key 的驼峰写法）。 */
export * from './departments'
export * from './jobs'
export * from './locations'
export * from './countries'
export * from './regions'
export * from './jobHistory'
export * from './jobGrades'
export * from './empDetails'
export * from './tDept'
export * from './tEmp'
export * from './orders'
export * from './users'
export * from './roles'
